export const friendsData = [
    {
        name: 'Bucky',
        surname: 'Barnes',
        email: 'wintersolder@gmail.com',
        iPath: 'https://wpkixx.com/html/winku/images/resources/friend-avatar.jpg',
        position: 'Student',
        status: 'online',
    },
    {
        name: 'Sarah',
        surname: 'Loren',
        email: 'bernes@gmail.com',
        iPath: 'https://wpkixx.com/html/winku/images/resources/friend-avatar2.jpg',
        position: 'Work At IBM',
        status: 'offline',
    },
    {
        name: 'Jason',
        surname: 'Borne',
        email: 'jasonb@gmail.com',
        iPath: 'https://wpkixx.com/html/winku/images/resources/friend-avatar3.jpg',
        position: 'Ftv Model',
        status: 'away',
    },
    {
        name: 'Cameron',
        surname: 'Diaz',
        email: 'jasonb@gmail.com',
        iPath: 'https://wpkixx.com/html/winku/images/resources/friend-avatar4.jpg',
        position: 'Work As Dancers',
        status: 'away',
    },
    {
        name: 'Daniel',
        surname: 'Warber',
        email: 'jasonb@gmail.com',
        iPath: 'https://wpkixx.com/html/winku/images/resources/friend-avatar5.jpg',
        position: 'Personal Business',
        status: 'offline',
    },
    {
        name: 'Andrew',
        surname: 'Watson',
        email: 'jasonb@gmail.com',
        iPath: 'https://wpkixx.com/html/winku/images/resources/friend-avatar6.jpg',
        position: 'Ftv Model',
        status: 'away',
    },
    {
        name: 'Amy',
        surname: 'Watson',
        email: 'jasonb@gmail.com',
        iPath: 'https://wpkixx.com/html/winku/images/resources/friend-avatar7.jpg',
        position: 'Work At IBM',
        status: 'online',
    },
    {
        name: 'Bucky',
        surname: 'Barnes',
        email: 'wintersolder@gmail.com',
        iPath: 'https://wpkixx.com/html/winku/images/resources/friend-avatar.jpg',
        position: 'Student',
        status: 'online',
    },
    {
        name: 'Sarah',
        surname: 'Loren',
        email: 'bernes@gmail.com',
        iPath: 'https://wpkixx.com/html/winku/images/resources/friend-avatar2.jpg',
        position: 'Work At IBM',
        status: 'offline',
    },
    {
        name: 'Jason',
        surname: 'Borne',
        email: 'jasonb@gmail.com',
        iPath: 'https://wpkixx.com/html/winku/images/resources/friend-avatar3.jpg',
        position: 'Ftv Model',
        status: 'away',
    },
    {
        name: 'Cameron',
        surname: 'Diaz',
        email: 'jasonb@gmail.com',
        iPath: 'https://wpkixx.com/html/winku/images/resources/friend-avatar4.jpg',
        position: 'Work As Dancers',
        status: 'away',
    },
    {
        name: 'Daniel',
        surname: 'Warber',
        email: 'jasonb@gmail.com',
        iPath: 'https://wpkixx.com/html/winku/images/resources/friend-avatar5.jpg',
        position: 'Personal Business',
        status: 'offline',
    },
    {
        name: 'Andrew',
        surname: 'Watson',
        email: 'jasonb@gmail.com',
        iPath: 'https://wpkixx.com/html/winku/images/resources/friend-avatar6.jpg',
        position: 'Ftv Model',
        status: 'away',
    },
    {
        name: 'Amy',
        surname: 'Watson',
        email: 'jasonb@gmail.com',
        iPath: 'https://wpkixx.com/html/winku/images/resources/friend-avatar7.jpg',
        position: 'Work At IBM',
        status: 'online',
    },
];
