export const photos = [
    'https://wpkixx.com/html/winku/images/resources/photo1.jpg',
    'https://wpkixx.com/html/winku/images/resources/photo2.jpg',
    'https://wpkixx.com/html/winku/images/resources/photo3.jpg',
    'https://wpkixx.com/html/winku/images/resources/photo4.jpg',
    'https://wpkixx.com/html/winku/images/resources/photo5.jpg',
    'https://wpkixx.com/html/winku/images/resources/photo6.jpg',
    'https://wpkixx.com/html/winku/images/resources/photo7.jpg',
    'https://wpkixx.com/html/winku/images/resources/photo8.jpg',
    'https://wpkixx.com/html/winku/images/resources/photo9.jpg',
    'https://wpkixx.com/html/winku/images/resources/photo10.jpg',
    'https://wpkixx.com/html/winku/images/resources/photo11.jpg',
    'https://wpkixx.com/html/winku/images/resources/photo12.jpg',
    'https://wpkixx.com/html/winku/images/resources/photo13.jpg',
    'https://wpkixx.com/html/winku/images/resources/photo-22.jpg',
    'https://wpkixx.com/html/winku/images/resources/photo-33.jpg',
];
